### ISSUE TITLE
npm start not working on windows

### ISSUE THREAD

**Issue by Jonatthu** [preboot/angular-webpack#209]
Windows 10, npm 3.10.3, and node 6.7.0

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.3
3 info using node@v6.7.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle app@0.0.0~prestart: app@0.0.0
6 silly lifecycle app@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle app@0.0.0~start: app@0.0.0
8 verbose lifecycle app@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle app@0.0.0~start: PATH: C:\Users\jonat\AppData\Roaming\nvm\v6.7.0\node_modules\npm\bin\node-gyp-bin;C:\Users\jonat\Desktop\angular2-webpack\node_modules.bin;C:\Program Files\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Users\jonat\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\ProgramData\chocolatey\bin;C:\Program Files\Java\jdk1.8.0_77\bin;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;C:\Program Files\Git\cmd;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\dotnet\;C:\Users\jonat.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update2\bin;C:\Users\jonat.dnx\bin;C:\Users\jonat\AppData\Roaming\npm;C:\Users\jonat\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files (x86)\Microsoft VS Code Insiders\bin;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;
10 verbose lifecycle app@0.0.0~start: CWD: C:\Users\jonat\Desktop\angular2-webpack
11 silly lifecycle app@0.0.0~start: Args: [ '/d /s /c', 'npm run server' ]
12 silly lifecycle app@0.0.0~start: Returned: code: 1  signal: null
13 info lifecycle app@0.0.0~start: Failed to exec start script
14 verbose stack Error: app@0.0.0 start: `npm run server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\jonat\AppData\Roaming\nvm\v6.7.0\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\jonat\AppData\Roaming\nvm\v6.7.0\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid app@0.0.0
16 verbose cwd C:\Users\jonat\Desktop\angular2-webpack
17 error Windows_NT 10.0.14393
18 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
19 error node v6.7.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error app@0.0.0 start: `npm run server`
22 error Exit status 1
23 error Failed at the app@0.0.0 start script 'npm run server'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the app package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run server
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs app
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls app
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Jonatthu** [comment]
I just needed to change the default port 8080 to other one thanks
