### ISSUE TITLE
 Promise is not defined

### ISSUE THREAD

**Issue by bhrt-DS** [preboot/angular-webpack#24]
Hi,
downloaded all dependencies but getting error,

ERROR in ./~/css-loader?sourceMap!./~/postcss-loader!./src/style/app.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/../workspace/angular-webpack/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/../workspace/angular-webpack/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:79:21)
    at Object.module.exports (../workspace/angular-webpack/node_modules/postcss-loader/index.js:47:10)
 @ ./src/style/app.css 4:14-132

**Comment by mikeerickson** [comment]
What version of Node do you have installed?  Promises require Node 4.x or greater 

$ node -v
