### ISSUE TITLE
Getting Error - "Unhandled Promise rejection: Cannot create property '__creationTrace__' on string" 

### ISSUE THREAD

**Issue by p4pramod** [preboot/angular-webpack#350]
I followed the steps in the readme and opened the folder in visual studio code but while loading the page 
 I can see an error and page is not working.

zone.js?fad3:655 Unhandled Promise rejection: Cannot create property '__creationTrace__' on string '__zone_symbol__optimizedZoneEventTask' ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot create property '__creationTrace__' on string '__zone_symbol__optimizedZoneEventTask'
    at Object.onScheduleTask (eval at 466 (polyfills.js:1405), <anonymous>:115:38)
    at ZoneDelegate.scheduleTask (eval at 467 (polyfills.js:1412), <anonymous>:404:51)
    at Object.onScheduleTask (eval at 467 (polyfills.js:1412), <anonymous>:300:29)
    at ZoneDelegate.scheduleTask (eval at 467 (polyfills.js:1412), <anonymous>:404:51)
    at Zone.scheduleTask (eval at 467 (polyfills.js:1412), <anonymous>:235:43)
    at Zone.scheduleEventTask (eval at 467 (polyfills.js:1412), <anonymous>:261:25)
    at eval (eval at 467 (polyfills.js:1412), <anonymous>:1561:29)
    at BrowserPlatformLocation.onPopState (eval at <anonymous> (vendor.js:125), <anonymous>:1970:60)
    at PathLocationStrategy.onPopState (eval at <anonymous> (vendor.js:195), <anonymous>:656:32)
    at new Location (eval at <anonymous> (vendor.js:195), <anonymous>:318:32)
    at AppModuleInjector.createInternal (module.ngfactory.js? [sm]:1)
    at AppModuleInjector.NgModuleInjector.create (eval at <anonymous> (vendor.js:73), <anonymous>:3764:76)
    at NgModuleFactory.create (eval at <anonymous> (vendor.js:73), <anonymous>:3737:18)
    at eval (eval at <anonymous> (vendor.js:73), <anonymous>:4975:61)
    at ZoneDelegate.invoke (eval at 467 (polyfills.js:1412), <anonymous>:391:26)
    at Object.onInvoke (eval at <anonymous> (vendor.js:73), <anonymous>:4352:37)
    at ZoneDelegate.invoke (eval at 467 (polyfills.js:1412), <anonymous>:390:32)
    at Zone.run (eval at 467 (polyfills.js:1412), <anonymous>:141:43)
    at NgZone.run (eval at <anonymous> (vendor.js:73), <anonymous>:4221:62)
    at PlatformRef_._bootstrapModuleFactoryWithZone (eval at <anonymous> (vendor.js:73), <anonymous>:4973:23)
    at eval (eval at <anonymous> (vendor.js:73), <anonymous>:5015:59)
    at ZoneDelegate.invoke (eval at 467 (polyfills.js:1412), <anonymous>:391:26)
    at Zone.run (eval at 467 (polyfills.js:1412), <anonymous>:141:43)
    at eval (eval at 467 (polyfills.js:1412), <anonymous>:832:57)
    at ZoneDelegate.invokeTask (eval at 467 (polyfills.js:1412), <anonymous>:424:31)
    at Zone.runTask (eval at 467 (polyfills.js:1412), <anonymous>:191:47)
    at drainMicroTaskQueue (eval at 467 (polyfills.js:1412), <anonymous>:596:35)
    at ZoneTask.invokeTask [as invoke] (eval at 467 (polyfills.js:1412), <anonymous>:503:21)
    at invokeTask (eval at 467 (polyfills.js:1412), <anonymous>:1349:10)
    at HTMLDocument.globalZoneAwareCallback (eval at 467 (polyfills.js:1412), <anonymous>:1358:13) TypeError: Cannot create property '__creationTrace__' on string '__zone_symbol__optimizedZoneEventTask'
    at Object.onScheduleTask (eval at 466 (http://localhost:9090/js/polyfills.js:1405:1), <anonymous>:115:38)
    at ZoneDelegate.scheduleTask (eval at 467 (http://localhost:9090/js/polyfills.js:1412:1), <anonymous>:404:51)
    at Object.onScheduleTask (eval at 467 (http://localhost:9090/js/polyfills.js:1412:1), <anonymous>:300:29)
    at ZoneDelegate.scheduleTask (eval at 467 (http://localhost:9090/js/polyfills.js:1412:1), <anonymous>:404:51)
    at Zone.scheduleTask (eval at 467 (http://localhost:9090/js/polyfills.js:1412:1), <anonymous>:235:43)
    at Zone.scheduleEventTask (eval at 467 (http://localhost:9090/js/polyfills.js:1412:1), <anonymous>:261:25)
    at eval (eval at 467 (http://localhost:9090/js/polyfills.js:1412:1), <anonymous>:1561:29)
    at BrowserPlatformLocation.onPopState (eval at <anonymous> (http://localhost:9090/js/vendor.js:125:1), <anonymous>:1970:60)
    at PathLocationStrategy.onPopState (eval at <anonymous> (http://localhost:9090/js/vendor.js:195:1), <anonymous>:656:32)
    at new Location (eval at <anonymous> (http://localhost:9090/js/vendor.js:195:1), <anonymous>:318:32)
    at AppModuleInjector.createInternal (ng:///AppModule/module.ngfactory.js:203:23)
    at AppModuleInjector.NgModuleInjector.create (eval at <anonymous> (http://localhost:9090/js/vendor.js:73:1), <anonymous>:3764:76)
    at NgModuleFactory.create (eval at <anonymous> (http://localhost:9090/js/vendor.js:73:1), <anonymous>:3737:18)
    at eval (eval at <anonymous> (http://localhost:9090/js/vendor.js:73:1), <anonymous>:4975:61)
    at ZoneDelegate.invoke (eval at 467 (http://localhost:9090/js/polyfills.js:1412:1), <anonymous>:391:26)
    at Object.onInvoke (eval at <anonymous> (http://localhost:9090/js/vendor.js:73:1), <anonymous>:4352:37)
    at ZoneDelegate.invoke (eval at 467 (http://localhost:9090/js/polyfills.js:1412:1), <anonymous>:390:32)
    at Zone.run (eval at 467 (http://localhost:9090/js/polyfills.js:1412:1), <anonymous>:141:43)
    at NgZone.run (eval at <anonymous> (http://localhost:9090/js/vendor.js:73:1), <anonymous>:4221:62)
    at PlatformRef_._bootstrapModuleFactoryWithZone (eval at <anonymous> (http://localhost:9090/js/vendor.js:73:1), <anonymous>:4973:23)
    at eval (eval at <anonymous> (http://localhost:9090/js/vendor.js:73:1), <anonymous>:5015:59)
    at ZoneDelegate.invoke (eval at 467 (http://localhost:9090/js/polyfills.js:1412:1), <anonymous>:391:26)
    at Zone.run (eval at 467 (http://localhost:9090/js/polyfills.js:1412:1), <anonymous>:141:43)
    at eval (eval at 467 (http://localhost:9090/js/polyfills.js:1412:1), <anonymous>:832:57)
    at ZoneDelegate.invokeTask (eval at 467 (http://localhost:9090/js/polyfills.js:1412:1), <anonymous>:424:31)
    at Zone.runTask (eval at 467 (http://localhost:9090/js/polyfills.js:1412:1), <anonymous>:191:47)
    at drainMicroTaskQueue (eval at 467 (http://localhost:9090/js/polyfills.js:1412:1), <anonymous>:596:35)
    at ZoneTask.invokeTask [as invoke] (eval at 467 (http://localhost:9090/js/polyfills.js:1412:1), <anonymous>:503:21)
    at invokeTask (eval at 467 (http://localhost:9090/js/polyfills.js:1412:1), <anonymous>:1349:10)
    at HTMLDocument.globalZoneAwareCallback (eval at 467 (http://localhost:9090/js/polyfills.js:1412:1),

**Comment by BndyNet** [comment]
Same problem.

**Comment by p4pramod** [comment]
import { Component } from '@angular/core'
@Component({
    selector: 'wel',
    template: `{{name}}
Welcome component
<span (click)="clicked()"></span>
`
})
export class WelcomeComponent {
    public name: string;
    constructor() {
        this.name = 'Test';
    }
    public clicked(event: any): void {
        this.name = 'Pramod';
    }
}
As soon as I add Event Binding it is failing other wise it works.

**Comment by Foxandxss** [comment]
The error comes from zone.js https://github.com/angular/zone.js/issues/832

**Comment by webdeveloperneeraj** [comment]
I am also getting this error using "zone.js": "^0.8.11",

**Comment by Foxandxss** [comment]
That is normal, that will install the broken version.

**Comment by p4pramod** [comment]
after changing to in package,json  "zone.js": "0.8.5"  it started working.
